import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  users: defineTable({
    externalId: v.string(),
    email: v.optional(v.string()),
    name: v.optional(v.string()),
    dailySpendLimit: v.optional(v.number()),
    maxTransactionAmount: v.optional(v.number()),
    autoApprovalThreshold: v.optional(v.number()),
    createdAt: v.number(),
  }).index('by_external_id', ['externalId']),
  conversations: defineTable({
    userId: v.id('users'),
    title: v.string(),
    createdAt: v.number(),
  }).index('by_user', ['userId']),
  purchaseIntents: defineTable({
    userId: v.id('users'),
    conversationId: v.optional(v.id('conversations')),
    merchant: v.string(),
    product: v.string(),
    amount: v.number(),
    currency: v.string(),
    reason: v.string(),
    status: v.union(
      v.literal('draft'),
      v.literal('pending_approval'),
      v.literal('approved'),
      v.literal('rejected'),
      v.literal('completed'),
    ),
    pravaIntentId: v.optional(v.string()),
    approvalId: v.optional(v.string()),
    transactionId: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_user', ['userId']),
  approvals: defineTable({
    userId: v.id('users'),
    purchaseIntentId: v.id('purchaseIntents'),
    status: v.union(
      v.literal('pending'),
      v.literal('approved'),
      v.literal('rejected'),
      v.literal('expired'),
      v.literal('processing'),
    ),
    pravaApprovalId: v.optional(v.string()),
    approvedAt: v.optional(v.number()),
    rejectedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_purchase_intent', ['purchaseIntentId']),
  transactions: defineTable({
    userId: v.id('users'),
    purchaseIntentId: v.id('purchaseIntents'),
    status: v.union(
      v.literal('created'),
      v.literal('authorized'),
      v.literal('submitted'),
      v.literal('settled'),
      v.literal('failed'),
      v.literal('cancelled'),
    ),
    merchant: v.string(),
    amount: v.number(),
    currency: v.string(),
    pravaTransactionId: v.optional(v.string()),
    receiptUrl: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_purchase_intent', ['purchaseIntentId']),
  orders: defineTable({
    userId: v.id('users'),
    transactionId: v.id('transactions'),
    orderNumber: v.string(),
    merchant: v.string(),
    status: v.string(),
    createdAt: v.number(),
  }).index('by_user', ['userId']),
  agentRuns: defineTable({
    userId: v.id('users'),
    conversationId: v.optional(v.id('conversations')),
    purchaseIntentId: v.optional(v.id('purchaseIntents')),
    agentType: v.union(
      v.literal('discovery'),
      v.literal('recommendation'),
      v.literal('intent'),
      v.literal('approval'),
      v.literal('purchase'),
      v.literal('replay'),
    ),
    status: v.union(v.literal('queued'), v.literal('running'), v.literal('succeeded'), v.literal('failed')),
    input: v.string(),
    output: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_user', ['userId']),
  replayEvents: defineTable({
    userId: v.id('users'),
    agentRunId: v.optional(v.id('agentRuns')),
    purchaseIntentId: v.optional(v.id('purchaseIntents')),
    eventType: v.union(
      v.literal('discovery'),
      v.literal('recommendation'),
      v.literal('intent'),
      v.literal('approval'),
      v.literal('purchase'),
      v.literal('replay'),
    ),
    title: v.string(),
    payload: v.string(),
    screenshotUrl: v.optional(v.string()),
    createdAt: v.number(),
  }).index('by_user', ['userId']),
  merchantSessions: defineTable({
    userId: v.id('users'),
    merchant: v.string(),
    status: v.union(v.literal('active'), v.literal('expired'), v.literal('revoked')),
    pravaMerchantToken: v.optional(v.string()),
    lastSyncedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_user', ['userId']),
});
